export const ADD_FAV = 'ADD_FAV';
export const REMOVE_FAV = 'REMOVE_FAV';

export const GET_RANDOM_CHARACTER_START = 'GET_RANDOM_CHARACTER_START';
export const GET_RANDOM_CHARACTER_SUCCESS = 'GET_RANDOM_CHARACTER_SUCCESS';
export const GET_RANDOM_CHARACTER_ERROR = 'GET_RANDOM_CHARACTER_ERROR';