export const GET_RANDOM_CHARACTER_START = 'GET_RANDOM_CHARACTER_START';
export const GET_RANDOM_CHARACTER_SUCCESS = 'GET_RANDOM_CHARACTER_SUCCESS';
export const GET_RANDOM_CHARACTER_ERROR = 'GET_RANDOM_CHARACTER_ERROR';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_SET_QUERY = 'SEARCH_SET_QUERY';